env:
    matrix:
    - IMAGE_TAG='master'
    - IMAGE_TAG='slave'
build:
  pre_ci:
    - if [[ $IMAGE_TAG == 'master' ]]; then mv module.master.yaml module.yaml; fi
    - if [[ $IMAGE_TAG == 'slave' ]]; then mv module.slave.yaml module.yaml; fi
    - docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag=luckyraul/powerdns:$IMAGE_TAG .
  pre_ci_boot:
    image_name: luckyraul/powerdns
    image_tag: $IMAGE_TAG
    pull: false
  ci:
    - pdns_server --version || true
  push:
     - docker push luckyraul/powerdns:$IMAGE_TAG
integrations:
    hub:
      - integrationName: Docker
        type: docker
        agent_only: true
