env:
    matrix:
    - IMAGE_TAG='master'
    - IMAGE_TAG='slave'
build:
  pre_ci:
    - apt-get install ruby
    - gem install puppet
    - puppet module install puppetlabs/image_build
    - sed -ie 's/--show_diff//g' /etc/puppetlabs/code/modules/image_build/templates/Dockerfile.erb
    - puppet docker build --image-name luckyraul/powerdns:$IMAGE_TAG-new
  pre_ci_boot:
    image_name: luckyraul/powerdns
    image_tag: $IMAGE_TAG
    pull: false
  ci:
    - pdns_server --version || true
  push:
    - docker push luckyraul/powerdns:$IMAGE_TAG-new
integrations:
    hub:
      - integrationName: Docker
        type: docker
        agent_only: true
