name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'master'
          - 'slave'
    steps:
      - uses: actions/checkout@v4

      - name: Test Ruby Version
        run: ruby -v
      - id: install_puppet
        name: Install Puppet
        continue-on-error: true
        run: |
          sudo apt-get -qqy install git sudo ruby
          sudo gem install puppet -v 7.27.0 --no-document
          sudo rm -fR /etc/puppetlabs/code/modules/image_build
          sudo git clone --single-branch --branch v2 https://github.com/luckyraul/puppetlabs-image_build.git /etc/puppetlabs/code/modules/image_build
      - name: Test Puppet Version
        run: puppet -V
      - name: Build Image
        run: sudo puppet docker build --image-name luckyraul/powerdns:${{ matrix.version }} --no-show-diff
      - name: Test Image Version
        run: docker run --rm luckyraul/powerdns:${{ matrix.version }} pdns_server --version || true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image
        run: |
          export IMAGE_NAME=luckyraul/powerdns:${{ matrix.version }}
          export IMAGE_ID=ghcr.io/luckyraul/powerdns:4.9-${{ matrix.version }}

          # Change all uppercase to lowercase
          export IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo $IMAGE_ID

          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
  post_build:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged ghcr LR
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          token: ${{ secrets.CR_PAT }}
          repository_owner: ${{ github.repository_owner }}
          owner_type: user
          package_name: powerdns
